name: uav_sim
channels:
  - defaults
dependencies:
  - ca-certificates=2025.9.9=haa95532_0
  - certifi=2022.12.7=py37haa95532_0
  - openssl=1.1.1w=h2bbff1b_0
  - python=3.7.16=h6244533_0
  - sqlite=3.50.2=hda9a48d_1
  - ucrt=10.0.22621.0=haa95532_0
  - vc=14.3=h2df5915_10
  - vc14_runtime=14.44.35208=h4927774_10
  - vs2015_runtime=14.44.35208=ha6b5a95_10
  - wincertstore=0.2=py37haa95532_2
  - pip:
      - cycler==0.10.0
      - kiwisolver==1.3.1
      - matplotlib==3.3.4
      - numpy==1.19.5
      - opencv-python==4.2.0.32
      - panda3d==1.10.6
      - pillow==9.4.0
      - pip==24.0
      - pyparsing==2.4.7
      - python-dateutil==2.9.0.post0
      - scipy==1.5.4
      - setuptools==68.0.0
      - six==1.17.0
      - torch==1.8.0
      - torchvision==0.9.0
      - typing-extensions==4.1.1
      - wheel==0.42.0
prefix: C:\Users\diego\miniconda3\envs\uav_sim
